In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv(r"C:\Users\Rawoo\OneDrive\Documents\Projects\walmart-sales-analysis-python\data\processed\walmart_cleaned.csv")
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Month_Name,Week,Quarter
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2,February,5,1
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,2010,2,February,6,1
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,2010,2,February,7,1
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,2010,2,February,8,1
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,2010,3,March,9,1

In [8]:
total_sales = df['Weekly_Sales'].sum()
total_sales

np.float64(6737218987.11)

In [9]:
avg_sales = df["Weekly_Sales"].mean()
avg_sales

np.float64(1046964.8775617715)

In [18]:
store_sales = df.groupby("Store")["Weekly_Sales"].sum().sort_values(ascending=False)
store_sales.head(10)

Store
20    3.013978e+08
4     2.995440e+08
14    2.889999e+08
13    2.865177e+08
2     2.753824e+08
10    2.716177e+08
27    2.538559e+08
6     2.237561e+08
1     2.224028e+08
39    2.074455e+08
Name: Weekly_Sales, dtype: float64

In [19]:
store_sales.tail(10)

Store
29    77141554.31
16    74252425.40
37    74202740.32
30    62716885.12
3     57586735.07
38    55159626.42
36    53412214.97
5     45475688.90
44    43293087.84
33    37160221.96
Name: Weekly_Sales, dtype: float64

In [16]:
yearly_sales = df.groupby("Year")["Weekly_Sales"].sum()
yearly_sales

Year
2010    2.288886e+09
2011    2.448200e+09
2012    2.000133e+09
Name: Weekly_Sales, dtype: float64

In [21]:
monthly_sales = (df.groupby(["Year", "Month","Month_Name"])["Weekly_Sales"].sum()
.reset_index().sort_values(by=["Year", "Month"]))
monthly_sales.head()

   Year  Month Month_Name  Weekly_Sales
0  2010      2   February  1.903330e+08
1  2010      3      March  1.819198e+08
2  2010      4      April  2.314124e+08
3  2010      5        May  1.867109e+08
4  2010      6       June  1.922462e+08

In [22]:
holiday_sales = df.groupby("Holiday_Flag")["Weekly_Sales"].agg(["mean","sum","count"])
holiday_sales

                      mean           sum  count
Holiday_Flag
0             1.041256e+06  6.231919e+09   5985
1             1.122888e+06  5.052996e+08    450

In [23]:
holiday_means = df.groupby("Holiday_Flag")["Weekly_Sales"].mean()
holiday_lift_pct = ((holiday_means[1] - holiday_means[0]) / holiday_means[0]) * 100
holiday_lift_pct

np.float64(7.839713033050179)

In [24]:
corr_matrix = df[["Weekly_Sales","Temperature","Fuel_Price","CPI","Unemployment"]].corr()

corr_matrix

              Weekly_Sales  Temperature  Fuel_Price       CPI  Unemployment
Weekly_Sales      1.000000    -0.063810    0.009464 -0.072634     -0.106176
Temperature      -0.063810     1.000000    0.144982  0.176888      0.101158
Fuel_Price        0.009464     0.144982    1.000000 -0.170642     -0.034684
CPI              -0.072634     0.176888   -0.170642  1.000000     -0.302020
Unemployment     -0.106176     0.101158   -0.034684 -0.302020      1.000000